### ISSUE TITLE
Make the point stop a the middle of canvas. 

### ISSUE THREAD

**Issue by aurelianonava** [aurelianonava/mhs#11]
Include an `if()` condition to stop the point right at the middle of canvas along the x axis.

**Comment by jdguzman230** [comment]
Mr. Nava, 
Check out my fix for issue #11.

**Comment by aurelianonava** [comment]
Juan,
Cool. I'll check it out.

**Comment by aurelianonava** [comment]
Good job Juan! I Merged your pull request to the mhs master branch.
